### ISSUE TITLE
Rendering empty string is an anti-pattern.

### ISSUE THREAD

**Issue by Bryan-Cee** [jillo-abdullahi/isacko-portfolio#1]
Hey man 👊 ,

Something new I learned recently and I noticed it in some of your code while I was messing around on GitHub. Here goes, rendering empty string is an antipattern because you create an node that is not used to render and item on the viewport, I would suggest this instead:

`{props.title && <span>{props.title}</span>}`

https://github.com/jillo-abdullahi/isacko-portfolio/blob/c3f48bcd5119de9d4c2e1eb1c3902b380f334409/src/components/ProjectsComponents/ProcessBox.js#L14

You can use the above pattern when you are sure to render something in this case:

`<span>{props.title ? props.title : "Default Title"}</span> `

I am still researching its impact on load time and how it optimizes your react app. I will write back on this issue when I get a satisfactory answer on why it would be good to abandon this pattern or not.

Cheers mate 👍 ,
Bryce

**Comment by Bryan-Cee** [comment]
Please have a look at examples of how conditional rendering has been used to get a better insight into my argument above: https://reactjs.org/docs/conditional-rendering.html

**Comment by jillo-abdullahi** [comment]
Hey Bryce,
Thanks for taking the time to go through the code man! I didn't think anyone was snooping around here 😆. I have been using both techniques back and forth but I think I will go with the one that you have recommended. It's much cleaner. Do let me know once you get something from your research. I will also poke around.

Cheers Bryce! 👊

**Comment by Bryan-Cee** [comment]
Jillo 😄,

So, I did a bit more reading and [this article ](https://www.robinwieruch.de/conditional-rendering-react) would give you a bit of gist. Here is an excerpt from the article about using `&&`.

> That's your way to go when you want to return nothing or an element inside JSX. It's also called short-circuit evaluation which makes it even more concise than a ternary operator.

It doesn't mention the issue we are discussing as an anti-pattern but it suggests using the `&&` operator over returning null or an empty string.
